import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns

# df = pd.read_csv("C:/44/pandas aiml/Transactions[1].csv")
# print(df)
# print(df.info())
# print(df.describe())
# print(df.isna().sum())
# print(df['category'].value_counts())
# print(df['customer_id'].value_counts())
# print(df.duplicated().sum())
# print(df['category'].unique())
# # plt.hist(data=df,x='category')
# # plt.show()
# # sns.countplot(data=df,x='category')
# # plt.show()
# sns.boxplot(data=df,x=df['category'],orient="v")
# # sns.barplot(data=df,x='category',y='price')
# # sns.lineplot(data=df,x='product_name',y='price')
# # sns.barplot(data=df,x='customer_id',y='quantity')
# # sns.barplot(data=df,x='customer_id',y='price')
# # sns.scatterplot(data=df,x='customer_id',y='price')
# plt.show()

# #central tendancy 
# # mean_price= df['price'].mean()
# # print("the maen of price is ",mean_price)
# # mean_quant = df['quantity'].mean()
# # print("the maen of price is ",mean_quant)
# # median_price= df['price'].median()
# # print("the median of price is ",median_price)
# # median_quant = df['quantity'].median()
# # print("the median of price is ",median_price)


# df = pd.read_csv("C:/44/pandas aiml/DataSets/DataSets/data_loan.csv")
# print(df)
# print(df['Loan_type'].unique())
# print(df.info())
# # sns.countplot(data=df,x='Loan_type')
# sns.countplot(data=df,x='Gender')
# sns.lineplot(data=df,x="Gender",y='Income')
# sns.histplot(data=df,x="Gender",kde=True)
# plt.show()
# sns.histplot(data=df,x="Loan_type",kde=True)
# plt.show()
# sns.histplot(data=df,x="Age",kde=True)
# plt.show()
# sns.histplot(data=df,x="Degree",kde=True)
# plt.show()
# sns.histplot(data=df,x="Income",kde=True)
# plt.show()
# sns.histplot(data=df,x="Credit_score",kde=True)
# plt.show()
# sns.histplot(data=df,x="Loan_length",kde=True)
# plt.show()
# sns.histplot(data=df,x="Signers",kde=True)
# plt.show()
# sns.histplot(data=df,x="Citizenship",kde=True)
# sns.boxplot(data=df,x="Income",y="Loan_type")
# plt.show()
# sns.boxplot(data=df,x="Default",y="Age")
# sns.boxplot(data=df,x="Credit_score",y="Loan_type")
# sns.barplot(data=df,x="Credit_score",y="Loan_type")
# sns.boxplot(data=df,x="Credit_score",y="Income")
# plt.show()
# sns.boxplot(data=df,x="Default",y="Income")
# plt.show()
# sns.barplot(data=df,x="Gender",y="Default")
# plt.show()
# sns.pairplot(data=df,x_vars=df)
# plt.xticks(rotation=90)

# plt.show()


# df = pd.read_csv("C:/44/pandas aiml/Pricing and Risk.csv")
# print(df.info())
# print(df.head())
# print(df.shape)
# print(df.duplicated().value_counts())
# print(df.duplicated().sum())
# print(df.isna().count())
# print(df['Claim_Amount'].unique())
# # sns.histplot(data=df,x="Policy_Type")
# # plt.show()
# sns.histplot(data=df,x="Premium_Amount",kde=True)
# print(df['Premium_Amount'].skew())
# print(df['Premium_Amount'].kurtosis())
# plt.show()
# sns.histplot(data=df,x="Insured_Amount")
# plt.show()
# sns.histplot(data=df,x="Location")
# plt.show()
# sns.histplot(data=df,x="Risk_Score")
# plt.show()
# sns.scatterplot(data=df,x="Insured_Amount",y='Premium_Amount')
# plt.show()
# sns.regplot(data=df,x="Insured_Amount",y='Premium_Amount')
# plt.show()
# sns.regplot(data=df,x="Insured_Amount",y='Risk_Score')
# plt.show()


# import math 
# # arr = list(range(-1,-100,1000))
# arr = np.random.randint(-100,0,100)
# df = pd.DataFrame(arr)
# # print(arr)
# v = sns.histplot(arr,kde=True)
# plt.xlim(-100,0)
# print(df.skew())
# print(df.kurtosis())
# plt.show()